### ISSUE TITLE
Floating point number for Zoom?

### ISSUE THREAD

**Issue by whyronimus** [misterhay/VISCA-IP-Controller#14]
Many thanks first for all your work on the visca over ip package!

One Question, or feature request: Currently, the "zoom" value can only be passed as integer.
Is it possible to send a floating point number? This would be great for smoother camera operation.

**Comment by misterhay** [comment]
Great idea, but unfortunately the VISCA protocol itself only allows integer values between 0 and 7 for the zoom speed.
