### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by digitalbird01** [misterhay/VISCA-IP-Controller#16]

**Comment by digitalbird01** [comment]
Hi
I have designed and built a number of  WIFI based PanTilt heads and am currently trying to add Visca control over UDP.
I am currently struggling to understand what return or response codes are expected from the camera system for a given command. Specifically

- When the serving software first tries to link up with the PTZ head
- After receiving any command
- after completing the command

Any help would be much appreciated

Colin

**Comment by misterhay** [comment]
Cool, that sounds like a great project.

Different camera makers can implement VISCA commands slightly differently, but generally a camera will acknowledge that it has received a command (return an ACK response) and then when it has completed the command.

|Command|Message Format|Example|
|-|-|-|
|acknowledge| `x0 4y FF`|`90 41 FF`|
|completed|`x0 5y FF`|`90 51 FF`|
|syntax error|`x0 60 02 FF`|`90 60 02 FF`|
|command buffer full|`x0 60 03 FF`|`90 60 03 FF`|
|command cancelled|`x0 6y 04 FF`|`90 60 04 FF`|
|no socket|`x0 6y 05 FF`|`90 60 05 FF`|
|command not executable|`x0 6y 41 FF`|`90 60 41 FF`|

`x` = device address + 8, usually `x = 9` for VISCA over IP
`y` = socket number, usually `y = 1`

You might also want to check out how cameras reply to inquiry commands.

For more information, check out the [Sony documentation](https://www.sony.net/Products/CameraSystem/CA/BRC_X400_SRG_X400/Technical_Document/E042100111.pdf) or the [PTZ Optics documentation](https://ptzoptics.com/wp-content/uploads/2020/11/PTZOptics-VISCA-over-IP-Rev-1_2-8-20.pdf).

**Comment by digitalbird01** [comment]
Thanks David

I have made a lot of progress over the past few days with all the main
functions now working with your software. Still a bit of work to do on the
finer details such as the expected return codes but I'm getting there. I
may have a few more questions for you as I go forward. I hope you
don't mind .
Thanks again for your reply.
Best regards
Colin
