### ISSUE TITLE
camera/get_pantilt_position has wrong byte numbering

### ISSUE THREAD

**Issue by stevehamnn** [misterhay/VISCA-IP-Controller#18]
get_pantilt_position lines 627-637 of camera.py uses the following byte numbering:

        pan_bytes = response[1:5]
        tilt_bytes = response[5:9]

I am using a Canon CR-N300 and I noticed it provides random/unpredictable tilt results. Investigating further, updating these lines accordingly produces the correct results:

        pan_bytes = response[2:6]
        tilt_bytes = response[6:10]

Not sure if it is a specific issue with just my camera model or not, but something I had to change to get the code to work correctly.

**Comment by misterhay** [comment]
I think you might be right, based on my reading of the VISCA specs. I'll submit a PR with the change, and hopefully someone else can test.
