### ISSUE TITLE
Apply a Version Tag to Project?

### ISSUE THREAD

**Issue by dhtseany** [misterhay/VISCA-IP-Controller#21]
Hi, could you please tag a release and specify a version so Github will create the .tar.gz's of your project? I was going to upload it to the [AUR](https://aur.archlinx.org) for people like myself that don't use pip but the lack of the tags is making the task harder than just asking you to make a tag. Thanks!

**Comment by misterhay** [comment]
Great idea, thank you. I've never done that before, but it hopefully it works as expected.
