### ISSUE TITLE
Focus far and focus near reversed for speed parameter of manual_focus()

### ISSUE THREAD

**Issue by balongi2** [misterhay/VISCA-IP-Controller#23]
The `speed` parameter of `manual_focus()` says:
>:param speed: -7 to 7 where positive integers focus near and negative integers focus far

However, positive integers (near) use `direction_hex == '2'` and negative numbers (far) use `direction_hex == '3'`, which is odds with the VISCA spec.

Far(Standard) | 8x 01 04 08 02 FF
Near(Standard) | 8x 01 04 08 03 FF

(Thanks for this useful module!)

**Comment by misterhay** [comment]
Great catch, thank you. PR created.
