### ISSUE TITLE
16 Camera Memory Slot Limit?

### ISSUE THREAD

**Issue by dhtseany** [misterhay/VISCA-IP-Controller#26]
Hi, why was the script limited to 16 camera memory slots? 

The AIDA PTZ20 supports 127 memory slots but when I attempt to call on a value past 15 I get the following error:

  File "/usr/lib/python3.12/site-packages/visca_over_ip/camera.py", line 615, in recall_preset
    raise ValueError('Preset num must be 0-15 inclusive')
ValueError: Preset num must be 0-15 inclusive

**Comment by misterhay** [comment]
It looks like according to the [documentation](https://aidaimaging.com/wp-content/uploads/2021/05/AIDA-IPNDI-PTZ-manual-V3.1.pdf) you are right. And making that change likely won't break things for other cameras, other than not getting the right error message if they call a value outside of the range of their camera. Will fix.

**Comment by misterhay** [comment]
Fixed

**Comment by dhtseany** [comment]
Perfect, I appreciate your assistance, would you mind giving the release a version bump so I can get it updated on the AUR? Thanks!

**Comment by misterhay** [comment]
Done :)
v0.5.0
