### ISSUE TITLE
[Bug]: ValueError: non-hexadecimal number found in fromhex() arg at position 12

### ISSUE THREAD

**Issue by dhtseany** [misterhay/VISCA-IP-Controller#33]
Hello, when trying to use the increased recall positions beyond 15 (16+) the script errors out with the following complaint:

```
Traceback (most recent call last):
  File "/opt/lcs-livetools/visca.py", line 16, in <module>
    cam.recall_preset(args.call_position)
  File "/usr/lib/python3.12/site-packages/visca_over_ip/camera.py", line 618, in recall_preset
    self._send_command(f'04 3F 02 0{preset_num:x}')
  File "/usr/lib/python3.12/site-packages/visca_over_ip/camera.py", line 49, in _send_command
    payload_bytes = preamble + bytearray.fromhex(command_hex) + terminator
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 12
```

**Comment by TechnoSwiss** [comment]
I've got a pull request waiting for approval that fixes this, if you what to try it https://github.com/misterhay/VISCA-IP-Controller/pull/31

**Comment by misterhay** [comment]
Merged

**Comment by dhtseany** [comment]
Hi, the problem isn't really resolved until somebody pushes a new version release, which is still sitting at v0.5.0 (October 21st). Please make a new release. Thanks!

**Comment by misterhay** [comment]
I had also pushed to PyPI: https://pypi.org/project/visca-over-ip/0.5.1/

But let me know if I've missed a step.

**Comment by dhtseany** [comment]
Hi David, go to https://github.com/misterhay/VISCA-IP-Controller/releases and click Add Release. That way it'll generate the needed .tar.gz and .zip package files that are used by external package managers. Thanks for your help!

**Comment by misterhay** [comment]
Right, forgot about that. It's done now.

Thank you :)
