### ISSUE TITLE
Remove 'set_' from function names

### ISSUE THREAD

**Issue by misterhay** [misterhay/VISCA-IP-Controller#6]
Do we want to remove the "set_" from function names to make them simpler? For example:

`camera.power(True)` instead of `camera.set_power(True)`

`camera.focus_mode('auto')` instead of `camera.set_focus_mode('auto')`

**Comment by Yook74** [comment]
For `set_focus_mode` I kind of want to leave it since there's the corresponding `get_focus_mode`. 

I'm fine with changing `set_power` to just `power` if you think that's better

**Comment by misterhay** [comment]
Hmm, good point. And as we implement more inquiry commands including `set_` or `get_` might not be a bad idea.
